ASFHyP3/hyp3-sdk

CHANGELOG.md
README.md
conda-env.yml
docs/README.md
docs/index.md
hyp3_sdk/exceptions.py
hyp3_sdk/hyp3.py
hyp3_sdk/jobs.py
hyp3_sdk/util.py
mkdocs.yml

* Simplifies the main README
* Sets up a documentation structure
* SDK API is auto-documented
* MkDocs site is gernateable/servable for development purposes, but **not deployed**
* SDK docs are intended to be consumed by the general HyP3 docs when it is built -- see ASFHyP3/ASFHyP3#20
* Add a bunch of docstrings and typehints throughout

More documentation updates

---

.github/workflows/release.yml

E.g.: https://github.com/ASFHyP3/GIS-tools/blob/develop/.github/workflows/release.yml#L44

Don't need refs/heads for branch spec in workflow dispatch

---

.github/workflows/static-analysis.yml
.github/workflows/test-and-build.yml
CHANGELOG.md
conda-env.yml
hyp3_sdk/__init__.py
setup.py

As of python 3.8, `importlib_metadata` is no longer required so that dependency has been removed.

Correctly specify minimum python version

---

CHANGELOG.md
conda-env.yml
hyp3_sdk/hyp3.py
hyp3_sdk/jobs.py
hyp3_sdk/util.py
setup.py
tests/test_jobs.py

Following best practices, 
* [`__str__`](https://docs.python.org/3/reference/datamodel.html#object.__str__) method causes jobs to print like:
```python
>>> print(job)
HyP3 RTC_GAMMA job dd884703-cdbf-47ff-848c-de1e2b9917c1
```
* [`__repr__`](https://docs.python.org/3/reference/datamodel.html#object.__repr__) method provides a copy-paste-able string representation of initializing the job:
```python
>>> print(repr(job))
Job.from_dict({'job_type': 'RTC_GAMMA', 'job_parameters': {'granules': ['S1A_IW_SLC__1SSV_20150621T120220_20150621T120232_006471_008934_72D8']}, 'job_id': 'dd884703-cdbf-47ff-848c-de1e2b9917c1', 'status_code': 'RUNNING', 'user_id': 'jhkennedy', 'request_time': '2021-02-16T20:56:04+00:00'})
```
* [`__str__`](https://docs.python.org/3/reference/datamodel.html#object.__str__) …

Better user info

---

conda-env.yml

colorama makes nested tqdm progress bars better on windows, but it's not required.
We can't include it in the conda-forge build (and still be `noarch`)  so may as well not include it here

Remove unnecessary package

---

.github/workflows/distribute.yml
.github/workflows/release.yml
.github/workflows/test-and-tag.yml
environment.yml

* moves package build and  pypi distribution to its own workflow
* drop s3pypi
* test and build -> test and tag
* mamba for faster conda env creation

Faster, cleaner github actions

---

docs/sdk_example.ipynb

Will need to release this (or `bumpless` merge to `main`) to get it into our documentation

Fix example notebook title

---

.github/workflows/distribute.yml
.github/workflows/test-and-tag.yml

Avoids `ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /tmp` error introduced with the [2.1.0 release](https://github.com/conda-incubator/setup-miniconda/releases/tag/v2.1.0)
The log output of an example failed action is at https://github.com/ASFHyP3/hyp3-sdk/runs/2231983477?check_suite_focus=true

pin setup-miniconda to 2.0.1

---

CHANGELOG.md
hyp3_sdk/__init__.py
hyp3_sdk/hyp3.py

It always feels wrong/weird to:
```
import hyp3_sdk as sdk
hyp3 = sdk.HyP3(sdk.HYP3_TEST)
```
even with the `as sdk` that's still *a lot* of HyP3s on a line. This is a bit better and more descriptive I think (and matches the fn argument name)
```
import hyp3_sdk as sdk
hyp3 = sdk.HyP3(sdk.TEST_API)
```

rename API URL constants

---

CHANGELOG.md
hyp3_sdk/hyp3.py
tests/test_hyp3.py

Need to add docstring language about the `include_los_displacement` parameter being depreciated.
Is it appropriate to log a warning when these functions are called with the depreciated parameter?

add include_displacement_maps parameter for insar jobs

---

environment.yml
setup.py

we should also consider freezing all dependancies and enabling dependabot

freeze responses to 0.14.0

---

README.md

HyP3 Docs points to this readme for the SDK content. I was hoping to make the external link behavior consistent with the rest of the HyP3 Docs content, but from the information I've been able to find, it sounds like GitHub flavored markdown does not support target=_blank. While I was here investigating, I thought I'd remove an extra period and add some capital letters.

Minor edits to hyp3-sdk readme

---

hyp3_sdk/jobs.py

Currently, when this error is thrown, it prints warning messages like:
```
Warning: Only succeeded jobs can be downloaded; job is PENDING.. Skipping download for HyP3 AUTORIFT job f978966b-b212-4767-8c46-219b3eb1354f.
```
Note the `..` after `PENDING`. 
This removes that double period.

Remove duplicated period in download warning

---

CHANGELOG.md
src/hyp3_sdk/__init__.py

This adds the `util` submodule to the `hyp3_sdk` API, which should fix IDE warnings when `hyp3_sdk.util` isn't explicitly imported:
and should also mean we don't need to explicitly call out `util` to document the SDK API reference:
https://github.com/ASFHyP3/hyp3-docs/blob/develop/docs/using/sdk_api.md

include `hyp3_sdk.util` in `__all__`

---

pyproject.toml

The HyP3 SDK README is at the top level of the repo. This fixes the path to the README so our PyPI project page isn't empty:

fix path to README

---

src/hyp3_sdk/util.py

#170  Currently when a user has not set a "Study Area" or accepted the EULA, they receive a 401 Unauthorized status code when authenticating with the Hyp3 SDK. The get_authenticated_session function raises a generic AuthenticationError whenever the response status code is greater than 399, telling the user that there is a problem with their credentials. 
However, it is possible for the user to get this AuthenticationError even if their credentials are correct. Using the response URL we can learn about why the user is receiving an error from the server. 
For example, if the user has not accepted the EULA, the server will respond with a response url that contains query params that contain useful error messages. 
`https://auth.asf.alaska.edu/login?error=access_denied&error_msg=Pre%20authoriza …

Issue 170: Adding better error message when user has not accepted the ASF EULA

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/test_hyp3.py

I named the new functions `submit_insar_isce_burst_job` and `prepare_insar_isce_burst_job` to match the job type `INSAR_ISCE_BURST`, but I'm open to a different naming scheme.
TODO:

Support `INSAR_ISCE_BURST` job type

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/test_hyp3.py

This:
* adds `HyP3.check_credits` method to check your remaining credits
* deprecates `HyP3.check_quota`
* changes `HyP3.check_quota`'s return type from `Optional[int]` to `Optional[float]`
* changes credits value to float in tests

Deprecate `HyP3.check_quota` in favor of `HyP3.check_credits`

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
src/hyp3_sdk/jobs.py
tests/test_hyp3.py
tests/test_jobs.py

Configurable job costs

---

.github/workflows/distribute.yml

PyPI uses a CDN, so we'd need to add a delay to this job. I've not actually seen a successful push to PyPI not then be pip installable, so I think we can just drop this instead.

Drop verify step for PyPI distribution

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/conftest.py
tests/test_hyp3.py

Reverts the unapproved user check added in <https://github.com/ASFHyP3/hyp3-sdk/pull/276>. See <https://github.com/ASFHyP3/hyp3-sdk/issues/285> for context.

Revert unapproved user check

---

.github/workflows/changelog.yml
.github/workflows/create-jira-issue.yml
.github/workflows/distribute.yml
.github/workflows/labeled-pr.yml
.github/workflows/release-template-comment.yml
.github/workflows/release.yml
.github/workflows/static-analysis.yml
.github/workflows/tag-version.yml
.github/workflows/test.yml
CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/conftest.py
tests/test_hyp3.py

Release v7.0.1

---

src/hyp3_sdk/hyp3.py
tests/test_hyp3.py

This:
* preserves both the submit and prepare interface for burst jobs:
* keeps the same number of positional arguments
* adds `granule1` and `granule2` as deprecated keyword-only arguments
* simplifies the locals logic, and pushes the warnings/raises to the prepare method as it's used by the submit method
Note: the prepare methods are public and used by users so we should maintain a 1-1 with the prepare methods and treat them as first class methods.

refactor submit and prepare insar busrt jobs

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/test_hyp3.py

Only added check to see if reference and secondary are equal length and contain more than 1 granule. Can add <= 15 check but not sure if that will increase/decrease in the future. Probably better to not couple this check to sdk version and leave in the api.

Add support for INSAR_ISCE_MULTI_BURST

---

CHANGELOG.md
src/hyp3_sdk/hyp3.py
tests/conftest.py
tests/test_hyp3.py

Support EDC Sandbox API URLs
