- tests/test_nothing.py
This is just a quick fix to get our checks to pass so we can close out #2 . Actually tests need to be added later
> Add no tests, but pass pytest

- .github/workflows/test-and-build.yml
> remove accidental hyp3lib test-and-build.yml

- hyp3_sdk/__init__.py
- hyp3_sdk/jobs.py
- tests/test_job.py
> add autorift to hyp3-sdk

- .github/workflows/labeled-pr.yml
> Check for semantic version labels on PRs to main

- .github/workflows/labeled-pr.yml
- CHANGELOG.md
- hyp3_sdk/util.py
> RELEASE 0.1.1 fixing auth url to allow login sucess

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> Allow searching by job name

- README.md
> Add get_jobs name parameter to README

- CHANGELOG.md
- README.md
- hyp3_sdk/hyp3.py
> RELEASE: allow sdk to search by name

- README.md
> Update README for docs website

- .github/workflows/changelog.yml
- CHANGELOG.md
> RELEASE: v0.2.1 -- try again

- CHANGELOG.md
- README.md
- docs/README.md
- docs/index.md
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- mkdocs.yml
> Update docs for feedback on release

- CHANGELOG.md
- README.md
- conda-env.yml
- docs/README.md
- docs/index.md
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- mkdocs.yml
> Release documentation update

- .github/workflows/release.yml
> Trigger SDK version bumb in HyP3 Docs

- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- tests/test_jobs.py
> minor changes

- .github/workflows/release.yml
> attempting to fix doc workflow

- CHANGELOG.md
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- tests/test_jobs.py
- tests/test_util.py
> support both strings and Paths in download functions

- CHANGELOG.md
- README.md
- docs/index.md
> update using to be representitive of current code base

- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test-and-build.yml
- CHANGELOG.md
- README.md
- conda-env.yml
- docs/index.md
- hyp3_sdk/__init__.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- setup.py
- tests/test_jobs.py
- tests/test_util.py
> RELEASE 0.3.1

- README.md
- docs/index.md
README looks like:
Docs looks the same *except without the badges*
> Add conda to install docs and some README badges

- CHANGELOG.md
- README.md
- docs/index.md
> fix order of parameters in submit job examples

- docs/index.md
> fix typo in index.md example

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> add default for download locations

- CHANGELOG.md
- README.md
- conda-env.yml
- docs/index.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> RELEASE: 0.3.2

- README.md
- docs/index.md
- hyp3_sdk/jobs.py
* Break long line in quickstart so we don't get a left-right slider
* More explicitly declare cwd as default for download files
> A couple of tweaks

- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Add a User-Agent header to SDK sessions

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> Fix batch constructor

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Add user warning for searches that return zero results

- CHANGELOG.md
- README.md
- docs/index.md
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- tests/test_hyp3.py
- tests/test_jobs.py
> Release Batch init fixes and agent header enhancement

- hyp3_sdk/asf_search.py
- tests/test_asf_search.py
> Baseline typo

- CHANGELOG.md
- conda-env.yml
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> All preparation and submission of multiple jobs

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> Iterable batch

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Public get job by id

- hyp3_sdk/hyp3.py
> descriptive submission errors

- CHANGELOG.md
- conda-env.yml
- hyp3_sdk/asf_search.py
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
- setup.py
- tests/test_asf_search.py
- tests/test_hyp3.py
- tests/test_jobs.py
* **~"minor" -- Minor changes to the API that do not break current workflows**
> Release v0.5.0

- setup.py
> fix indentation typo in setup.py

- hyp3_sdk/hyp3.py
> Fix whitespace

- CHANGELOG.md
- docs/sdk_example.ipynb
- hyp3_sdk/hyp3.py
- hyp3_sdk/util.py
> Add prompt for username password to HyP3 class init

- hyp3_sdk/asf_search.py
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- tests/test_exceptions.py
> make helper raise for status functions private

- .github/workflows/distribute.yml
> fix distribute workflow

- .github/workflows/release.yml
Reflects changes in ASFHyP3/hyp3-docs#56
> change docs repo

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> bring hyp3-sdk to be compatible with HyP3 v1.0.0

- CHANGELOG.md
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- tests/test_exceptions.py
- tests/test_jobs.py
> quick fixes

- .github/workflows/distribute.yml
- .github/workflows/release.yml
- CHANGELOG.md
- docs/sdk_example.ipynb
- hyp3_sdk/exceptions.py
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- tests/test_exceptions.py
- tests/test_hyp3.py
- tests/test_jobs.py
> RELEASE: 1.0.0

- .github/workflows/distribute.yml
> fix bug in distribute workflow

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
Pending merge of https://github.com/ASFHyP3/hyp3/pull/384 adding the parameter to the HyP3 API.
> add dem_name parameter for rtc jobs

- .github/workflows/distribute.yml
- .github/workflows/test-and-tag.yml
- CHANGELOG.md
- environment.yml
- hyp3_sdk/hyp3.py
- postBuild
- tests/test_hyp3.py
Depends on https://github.com/ASFHyP3/hyp3/pull/390
* **~"minor" -- Minor changes to the API that do not break current workflows**
> Release dem_name parameter for RTC

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> add include_inc_map parameter for InSAR jobs

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Release include_inc_map parameter for InSAR jobs

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> expose new include_dem parameter for insar jobs

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Release include_dem parameter for InSAR jobs

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> expose include_unwrapped_phase parameter for insar jobs

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Release include_wrapped_phase option for InSAR jobs

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> Adding Missing Methods to Batch Class

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Removed FoundZeroJobs warning, and set UTC to be the default timezone.

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
- hyp3_sdk/util.py
See #92 
Verified works with:
* no jupyter anything installed for both console and notebook
* Just an ipykernel installed for both console and notebook
* jupyter metapackage (with ipykernel) installed for both console and notebook
> Handle missing ipywidgets when using a tqdm progress bar

- tests/test_hyp3.py
> Tests for find_jobs() w/ and w/o timezone

- .github/workflows/test-and-tag.yml
> fix typo in test-and-tag.yml

- hyp3_sdk/hyp3.py
> update include_inc_map parameter help

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> fix bug in find_jobs using status_code

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Release: 1.3.1

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Add apply water mask option for InSAR

- CHANGELOG.md
- hyp3_sdk/asf_search.py
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Changelog cleanup

- .github/CODEOWNERS
> add .github/CODEOWNERS

- .github/CODEOWNERS
- CHANGELOG.md
- hyp3_sdk/asf_search.py
- hyp3_sdk/hyp3.py
- tests/test_hyp3.py
* **~"minor" -- Minor changes to the API that do not break current workflows**
> Release v1.4.0

- environment.yml
- hyp3_sdk/util.py
- setup.py
- tests/test_util.py
> update tests to not provide chunk_size none to requests.get

- CHANGELOG.md
- hyp3_sdk/jobs.py
> Add processing_time_in_seconds, add a TODO

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> Update `check_quota` return type

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> Release 1.5.1

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> Job.expired() now returns False if expiration_time is None

- CHANGELOG.md
- hyp3_sdk/jobs.py
- tests/test_jobs.py
> Release 1.6.0

- CHANGELOG.md
- hyp3_sdk/jobs.py
> Add Job.subscription_id field

- .github/workflows/static-analysis.yml
> switch to re-usable github action for secrets analysis

- .github/workflows/static-analysis.yml
- CHANGELOG.md
- hyp3_sdk/jobs.py
> Release 1.6.1

- CHANGELOG.md
- hyp3_sdk/jobs.py
```python
>>> jobs = hyp3.find_jobs()
>>> len(jobs)
426
>>> pprint(jobs[0].to_dict())
{'browse_images': ['https://d3gm2hf49xd6jj.cloudfront.net/be55a370-2090-4622-933c-b8abcd93ad2e/S2B_13CES_20200105_0_L1C_X_S2B_13CES_20200315_0_L1C_G0120V02_P000_IL_ASF_OD.png'],
'expiration_time': '2022-09-30T00:00:00+00:00',
'files': [{'filename': 'S2B_13CES_20200105_0_L1C_X_S2B_13CES_20200315_0_L1C_G0120V02_P000_IL_ASF_OD.nc',
's3': {'bucket': 'hyp3-edc-prod-contentbucket-1fv14ed36ifj6',
'key': 'be55a370-2090-4622-933c-b8abcd93ad2e/S2B_13CES_20200105_0_L1C_X_S2B_13CES_20200315_0_L1C_G0120V02_P000_IL_ASF_OD.nc'},
'size': 200290,
'url': 'https://d3gm2hf49xd6jj.cloudfront.net/be55a370-2090-4622-933c-b8abcd93ad2e/S2B_13CES_20200105_0_L1C_X_S2B_13CES_20200315_0_L1C_G0120V02_P000_IL_ASF_OD.nc'}],
'job_id': …
```
> replace Job.processing_time_in_seconds with Job.processing_times

- CHANGELOG.md
- README.md
- hyp3_sdk/jobs.py
* **~"minor" -- Minor changes to the API that do not break current workflows**
> Release v1.7.0

- CHANGELOG.md
- docs/sdk_example.ipynb
> update for S2 from Google cloud

- CHANGELOG.md
- docs/sdk_example.ipynb
> Update Autorift naming for ESA only

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> add optional decibel argument

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> Release 1.7.2 - add decibel option

- CHANGELOG.md
- hyp3_sdk/hyp3.py
> Add 10m resolution as option for RTC

- CHANGELOG.md
- hyp3_sdk/hyp3.py
- hyp3_sdk/jobs.py
Add in 10 m RTC option to `submit_rtc_job` and `prepare_rtc_job` functions.
> Release v1.7.3

- .github/workflows/static-analysis.yml
> fix tag in reusable workflow

- CHANGELOG.md
- src/hyp3_sdk/__init__.py
- src/hyp3_sdk/config.py
- src/hyp3_sdk/hyp3.py
- src/hyp3_sdk/util.py
- tests/test_hyp3.py
- tests/test_util.py
See https://github.com/ASFHyP3/hyp3-sdk/issues/170 and https://github.com/ASFHyP3/hyp3-sdk/pull/194
TODO:
> Earthdata auth errors

- CHANGELOG.md
- docs/search_other_user_jobs.ipynb
- src/hyp3_sdk/hyp3.py
Fixes potentially breaking changes introduced by https://github.com/ASFHyP3/hyp3-sdk/pull/218
> Move `user_id` to end of `find_jobs` param list

- CHANGELOG.md
- src/hyp3_sdk/hyp3.py
- tests/test_hyp3.py
> Add `phase_filter_parameter` for InSAR jobs

- .github/workflows/changelog.yml
- .github/workflows/create-jira-issue.yml
- .github/workflows/distribute.yml
- .github/workflows/labeled-pr.yml
- .github/workflows/release-template-comment.yml
- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tag-version.yml
- .github/workflows/test.yml
- CHANGELOG.md
- src/hyp3_sdk/hyp3.py
- src/hyp3_sdk/jobs.py
- tests/conftest.py
- tests/test_hyp3.py
- tests/test_jobs.py
> Release v6.0.0

- .github/workflows/changelog.yml
- .github/workflows/create-jira-issue.yml
- .github/workflows/distribute.yml
- .github/workflows/labeled-pr.yml
- .github/workflows/release-template-comment.yml
- .github/workflows/release.yml
- .github/workflows/static-analysis.yml
- .github/workflows/tag-version.yml
- .github/workflows/test.yml
- .trufflehog.txt
- CHANGELOG.md
- src/hyp3_sdk/hyp3.py
- src/hyp3_sdk/jobs.py
- tests/test_hyp3.py
- tests/test_jobs.py
Validated both new methods against `hyp3-test` and `hyp3-enterprise-test`.
> Release v6.1.0

- .github/workflows/tag-version.yml
Adding this comment so that we see it in case we use this repo as the template for a new repo in the future.
> add comment for v0.0.0 tag

- CHANGELOG.md
- README.md
- src/hyp3_sdk/exceptions.py
- src/hyp3_sdk/hyp3.py
- tests/test_exceptions.py
- tests/test_hyp3.py
> Add OPERA RTC as job type

- CHANGELOG.md
- src/hyp3_sdk/hyp3.py
- tests/conftest.py
- tests/test_hyp3.py
See https://github.com/ASFHyP3/hyp3-sdk/issues/369
TODO:
> Do not update cookie domain for non-asf hosts when token is given
